export default {
  // currentUser
  SET_CURRENTUSER_SCREEN_NAME: 'SET_CURRENTUSER_SCREEN_NAME',
  SET_CURRENTUSER_PHONE: 'SET_CURRENTUSER_PHONE',
  SET_CURRENTUSER_EMAIL: 'SET_CURRENTUSER_EMAIL',

  // tweetCardPopup
  TWEETCARD_POPUP_SET_USER: 'TWEETCARD_POPUP_SET_USER',
  TWEETCARD_POPUP_SET_POSITION: 'TWEETCARD_POPUP_SET_POSITION',

  // modal
  SET_UP_MODAL: 'SET_UP_MODAL',

  // recommendPage
  SET_RECOMMENDPAGE_RECOMMEND_QUERY: 'SET_RECOMMENDPAGE_RECOMMEND_QUERY',
  SET_RECOMMENDPAGE_SEARCH_QUERY: 'SET_RECOMMENDPAGE_SEARCH_QUERY',

  // theme
  SET_LIGHT: 'SET_LIGHT',
  SET_DARK: 'SET_DARK',
};
